- README.md
This PR for testing CD/CI of staging only
> Add logo to Readme

- db/seeds/3_volunteer.rb
Добавил, в seed   поля имени , фамилии , телефона для  волонтера
> Fix seed project

- app/views/admin/reports/template.xlsx.axlsx
https://sentry.ds.agency/organizations/helphub/issues/3/?project=2&query=is%3Aunresolved
> Fixing the bug with the length of the sheet name

- app/views/devise/registrations/new.html.erb
- app/views/shared/_registration_steps.html.erb
- config/locales/ru.yml
* Update steps
* Add a link to privacy politics
> Update registration form

- app/mailers/helphub_devise_mailer.rb
- app/models/user.rb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/pages/confirm_email.html.erb
- app/views/pages/waiting_for_moderator.html.erb
- config/initializers/devise.rb
- config/locales/ru.yml
* email validation
* confirm email letter
* fixes
> Registration fixes

- app/models/help_request.rb
- app/presenters/api/help_request_presenter.rb
- app/searchers/api/help_requests_searcher.rb
- app/use_cases/admin/help_request_cases/create.rb
- db/migrate/20210622071908_add_creator_id_to_help_requests.rb
- db/schema.rb
- spec/factories/help_request_factory.rb
- spec/requests/api/v1/help_requests_spec.rb
- spec/requests/api/v2/help_requests_spec.rb
- spec/searchers/dashboard/admin_searcher_spec.rb
- spec/workers/recurring_help_request_worker_spec.rb
```
[{
"id": 98,
"title": "МОя просьбюааа",
"state": "active",
"comment": "comment comment comment",
"number": "34",
"mediated": false,
"meds_preciption_required": false,
"volunteer_id": null,
"period": 10,
"recurring": true,
"address": "Moscow Center Lenina 1",
"detailed_address":{"city": "Moscow", "district": "Center", "street": "Lenina", "house": null,…},
"lonlat":{
"type": "Point",
"coordinates":[
37.66940591308594,
55.71252005362048
]
},
"distance": "",
"geo_salt": true,
"custom_fields":[{"name": "любимо животное", "value": "awdawdd 2 2222", "type": "string"…],
"phone": "+79*******11",
"date_begin": null,
"date_end": null,
"created_at": 1624259830,
"updated_at": 1624346762,
"activated_days_ago": 1,
"creator_phone": "+79999999999"
}]
```
> Add creator to help_request to render moderator phone in API

- app/controllers/admin/help_request_kinds_controller.rb
- app/controllers/application_controller.rb
- app/models/custom_field.rb
- app/models/help_request_kind.rb
- app/views/layouts/application.html.erb
- config/locales/models/en.yml
- config/locales/models/ru.yml
* CustomField validation
* HelpRequestKind validation
* Smart Bootstrap flash helper
> Prevent custom fields removing if they filled with values

- app/views/admin/help_requests/_filters.html.erb
- app/views/admin/users/_filters.html.erb
https://github.com/helphubteam/helphub-archived/issues/282
> Align search fields left

- app/views/admin/help_requests/_filters.html.erb
> Replace "reset filters" button in help_requests

- .github/workflows/deploy_production.yml
- .github/workflows/deploy_staging.yml
1. Delete cancel-in-progress:true in staging pipe
2. Change concurency group name in staging pipe
3. Add concurency group to prod pipe
> Update github actions

- app/controllers/api/v3/help_requests_controller.rb
- app/presenters/api/help_request_presenter.rb
- app/presenters/api/v3/help_request_presenter.rb
- app/use_cases/api/v3/help_request_cases/assign.rb
- app/use_cases/api/v3/help_request_cases/base.rb
- app/use_cases/api/v3/help_request_cases/refuse.rb
- app/use_cases/api/v3/help_request_cases/submit.rb
- config/routes.rb
- spec/factories/custom_field_factory.rb
- spec/requests/api/v2/help_requests_spec.rb
- spec/requests/api/v3/help_requests_spec.rb
1) Keep v1/v2 help requests in the same shape
2) Add phone field structure support to V3
3) Cover help_requests response data with tests
> Add API v3 help requests

- app/controllers/admin/help_requests_controller.rb
- app/searchers/help_requests_searcher.rb
- app/views/admin/help_requests/_filters.html.erb
- config/locales/en.yml
- config/locales/ru.yml
> Add filter help requests by creator

- app/models/help_request.rb
- app/models/help_request_kind.rb
We keep it the same no matter if custom fields were updated
Fix for https://github.com/helphubteam/helphub/issues/75
> Fix custom values order

- app/javascript/custom-fields/components/checkbox.vue
- app/models/custom_value.rb
* Restyle admin checkbox custom field
* Add custom value uniq validation
> Update checkbox custom field

- .github/workflows/deploy_production.yml
- docker-compose.prod.yml
Github actions and docker update for server migration
> New deploy GitHub actions

- app/controllers/admin/help_request_kinds_controller.rb
- app/views/admin/help_request_kinds/_form.html.erb
- spec/requests/admin/help_request_kinds_spec.rb
> Hide custom fields on help request kind creation

- app/controllers/admin/help_requests_controller.rb
- app/models/concerns/roles_helpers.rb
- app/models/help_request_log.rb
- app/views/admin/help_requests/_filters.html.erb
- app/views/admin/help_requests/_logs.html.erb
- app/views/admin/reports/template.xlsx.axlsx
- app/views/admin/users/_activity.html.erb
- config/locales/models/ru.yml
- config/locales/ru.yml
Fixes for:
#96
#95
#94
#93
#92
> Handler testing comments

- app/controllers/admin/users_controller.rb
- app/views/admin/users/_form.html.erb
- app/views/shared/_menu.html.erb
- config/locales/models/ru.yml
- config/locales/ru.yml
- rename content manager role name
- remove menu for content managers
- user edit redirects back to help request for them
- remove delete button
- cancel button redirects back to help request for them
> Apply content manager role fixes

- app/views/user_mailer/moderator_confirmation.html.erb
https://github.com/helphubteam/helphub/issues/102
> Fix mailto href in email message.

- .dockerDev/Dockerfile
hotfix https://discord.com/channels/734387076715380776/734387734604546048/908403112723771442
> Fix build dev

- .github/workflows/deploy_staging_new.yml
- docker-compose.stag.yml
> Deploy new

- .dockerDev/Dockerfile
- .github/workflows/deploy_production.yml
- Gemfile
- Gemfile.lock
- app/assets/stylesheets/admin/help_request.scss
- app/controllers/api/v3/help_requests_controller.rb
- app/models/help_request_log.rb
- app/use_cases/api/v3/help_request_cases/base.rb
- app/use_cases/api/v3/help_request_cases/submit.rb
- app/views/admin/help_requests/_logs.html.erb
- config/locales/models/ru.yml
- docker-compose.prod.yml
- docker-compose.stag.yml
- docker-compose.stg.yml
- docker-compose.yml
> Add photos to HelpRequestLog
